# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180114_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestMessage',
        ),
    ]
